---
title: "Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(twitteR)
library(ROAuth)
library(devtools)
library(httr)
library(jsonlite)
library(readr)
library(RDS)
library(lubridate)
library(magrittr)
library(rtweet)
```

```{r}
# Download "cacert.pem" file
#download.file(url="http://curl.haxx.se/ca/cacert.pem",destfile="cacert.pem")

#create an object "cred" that will save the authenticated object that we can use for later sessions
# cred <- OAuthFactory$new(consumerKey='xa1wWUs5shIvAcot57r7xhQZE',
#      consumerSecret='AQFXM5ZQ2YMoq1qIhzlYsU5j7ASULzT8wwEw9He6upZVnMRMKw',
#      requestURL='https://api.twitter.com/oauth/request_token',
#      accessURL='https://api.twitter.com/oauth/access_token',
#     authURL='https://api.twitter.com/oauth/authorize')
# Executing the next step generates an output --> To enable the connection, please direct your web browser to: <hyperlink> . Note:  You only need to do this part once

 # cred$handshake(cainfo="cacert.pem")

 #  save(cred, file="twitter authentication.Rdata")
   
   load("twitter authentication.Rdata")
   
  consumer_key<-"xa1wWUs5shIvAcot57r7xhQZE"
  consumer_secret<-"AQFXM5ZQ2YMoq1qIhzlYsU5j7ASULzT8wwEw9He6upZVnMRMKw"
  access_token<-"805657646-4fqd7p414MUdX5Cg01wcqEToqmtmdsPM37ieg8gX"
  access_secret<-"6nxHYM2GTCtaLG9whtTKsdqexqellVBmtneZC7X5POPEP"


  setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
```


```{r}
  no.of.tweets <- 10000
  
    twitter_function<-function(hashtag) {
    
  tweets_w_hashtag <- searchTwitter(hashtag, 
                                   n=no.of.tweets, 
                                   lang="en", 
                                   since=as.char(Sys.Date()-7),
                                   until=as.char(Sys.Date()))
  
  hashtag_df <- tbl_df(map_df(tweets_w_hashtag, as.data.frame))
 
  hashtag_df<-hashtag_df%>%mutate(week=week(Sys.Date()))%>%
                        group_by(week)%>%
                        summarise(count=n())
    return(hashtag_df)
  }
insomnia_tweets<-twitter_function('#insomnia')
cantsleep_tweets<-twitter_function('#cantsleep')
wideawake_tweets<-twitter_function('#wideawake')
nosleep_tweets<-twitter_function('#nosleep')

master_table<-insomnia_tweets%>%full_join(cantsleep_tweets,by='week')%>%
                  full_join(wideawake_tweets,by='week')%>%
                  full_join(nosleep_tweets, by='week')%>%
                  mutate(insomnia_count = count.x, cantsleep_count = count.y, wideawake_count = count.x.x, nosleep_count = count.y.y)%>%
                  summarise(week,totalcount=insomnia_count+cantsleep_count+wideawake_count+nosleep_count)
master_table
```

```{r}
#three_am_function<-function(all) {
    
  #all_tweets <- searchTwitter(all,
                                  # n=5000, 
                                   #lang="en", 
                                   #since=as.char(Sys.Date()-7),
                                   #until=as.char(Sys.Date()))
  
 # three_am_tweets <- tbl_df(map_df(all_tweets, as.data.frame))
  
   # return(three_am_tweets)
 # }
#test_tweets<-three_am_function(' ')
#test_tweets<-test_tweets%>%
             #mutate(time=format(created,format='%H:%M:%S'))
#there are no tweets in the early AM hours: only those leading up to midnight
```

```{r}
#one minute of tweets in the eastern time zone
eastern_time_zone <- stream_tweets(
  c(-82.5, 25, -70, 47),
  timeout = 60)

three_am_tweets <- eastern_time_zone %>%
                        mutate(week=week(Sys.Date()))%>%
                        group_by(week)%>%
                        summarise(late_night_count=n(), week)
```


```{r}
lunar_stats <- function(file_json){
    
    lunar_data<-fromJSON(file_json)
    lunar_data_frame<-as.data.frame(lunar_data)
    
   
  return(lunar_data_frame)
}

lunar_statistics<-lunar_stats('http://api.usno.navy.mil/moon/phase?year=2017')
lunar_statistics = lunar_statistics %>% select(date=phasedata.date,
                          phase=phasedata.phase,
                          time=phasedata.time)%>%
                     mutate(Date=as.Date((date),"%Y %b %d"), week = as.numeric(week(Date)))%>%
                     select(phase,Date,time,week)
```



```{r}

#added three am tweets to the master table
master_table%>%full_join(lunar_statistics, by = 'week')%>%
               full_join(three_am_tweets, by = 'week')%>%
               group_by(phase)%>%
               summarise(total_hashtag_tweet_count = sum(totalcount,na.rm = TRUE), average_hashtag_tweet_count = total_tweet_count/13, num_late_night_tweets = sum(late_night_count))
```

